### ISSUE TITLE
Compiling on Ubuntu 16.04

### ISSUE THREAD

**Issue by JeroenMerks** [NVlabs/nvbio#14]
Dear developers,

On my following machine I consistently get the following errors when I'm trying to compile nvbio:=

```
/usr/include/string.h: In function ‘void* __mempcpy_inline(void*, const void*, size_t)’:
/usr/include/string.h:652:42: error: ‘**memcpy**’ was not declared in this scope
   return (char *) memcpy (__dest, __src, __n) + __n;
```
I'm trying to compile with gcc-4.8 and CUDA 6.5.
Is the CUDA version too new or too old?

Any help would be appreciated.

**Comment by nsubtil** [comment]
This sounds related to this other issue that was reported on Caffe: https://groups.google.com/forum/#!msg/caffe-users/Tm3OsZBwN9Q/XKGRKNdmBAAJ

It's not clear why, but compiling with -D_FORCE_INLINES apparently helps. Might be worth a try here as well.

**Comment by JeroenMerks** [comment]
Thank you very much, that seems to help.
But when almost everything is compiled, I get 

```
CMakeFiles/nvBowtie.dir/nvBowtie.cpp.o: In function `main':
nvBowtie.cpp:(.text.startup+0x9ea): undefined reference to `nvbio::bowtie2::cuda::parse_options(nvbio::bowtie2::cuda::Params&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, bool)'
nvBowtie.cpp:(.text.startup+0x1c03): undefined reference to `nvbio::bowtie2::cuda::load_options(char const*)'
nvBowtie.cpp:(.text.startup+0x1c25): undefined reference to `nvbio::bowtie2::cuda::parse_options(nvbio::bowtie2::cuda::Params&, std::map<std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&, bool)'
collect2: ld returned 1 exit status
make[2]: *** [nvBowtie/nvBowtie] Error 1
make[1]: *** [nvBowtie/CMakeFiles/nvBowtie.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by JeroenMerks** [comment]
Compiling with the make -i flag makes the compilation continue and at least compile important files like nvBWT and nvBowtie.

**Comment by r-barnes** [comment]
master now includes fixes to permit building with newer versions of CUDA and GCC. Given that this bug results from using older compilers, I think it can be closed (@foertter ).
